from selenium import webdriver
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.keys import Keys

driver = webdriver.Chrome("E:\chrome driver\chromedriver_win32\chromedriver.exe")
driver.maximize_window()
driver.get("http://demo.automationtesting.in/Register.html")
driver.find_element_by_xpath("//input[@ng-model='FirstName']").send_keys('sonu')
driver.find_element_by_xpath("//input[@ng-model='LastName']").send_keys('Garimella')
driver.find_element_by_xpath("//textarea[@ng-model='Adress']").send_keys('India')
driver.find_element_by_xpath("//input[@type='email']").send_keys("sonu@yahoo.com")
driver.find_element_by_xpath("//input[@type='tel']").send_keys("9343434343")
driver.find_elements_by_xpath("//input[@type='radio']")[1].click()
driver.find_element_by_id("checkbox1").click()
driver.find_element_by_id("checkbox3").click()
driver.find_element_by_id("msdd").click()
driver.find_element_by_xpath("//a[text()='Catalan']").click()
select1 = Select(driver.find_element_by_id("Skills"))
select1.select_by_value("Adobe Photoshop")
select2 = Select(driver.find_element_by_id("countries"))
select2.select_by_value("Albania")
select3 = Select(driver.find_element_by_id("yearbox"))
select3.select_by_value("1918")
select4 = Select(driver.find_element_by_xpath("//select[@ng-model='monthbox']"))
select4.select_by_value("March")
select5 = Select(driver.find_element_by_id("daybox"))
select5.select_by_value("10")
driver.find_element_by_id("firstpassword").send_keys("Google@123")
driver.find_element_by_id("secondpassword").send_keys("Google@123")
driver.find_element_by_id("submitbtn").click()