from selenium import webdriver
import time

driver = webdriver.Chrome("E:\SeleniumPrgms\drivers\chromedriver.exe")
driver.get("https://freecrm.co.in/")
driver.maximize_window()
login_element=driver.find_element_by_xpath("//span[text()='Log In']")
login_element.click()
email_element=driver.find_element_by_xpath("//input[@name='email']")
password_element=driver.find_element_by_xpath("//input[@name='password']")
email_element.send_keys("vaishu.mru@gmail.com")
password_element.send_keys("Vaish1234")
crm_login_element=driver.find_element_by_xpath("//div[text()='Login']")
crm_login_element.click()
time.sleep(5)
contact_element=driver.find_element_by_xpath("//span[text()='Contacts']")
contact_element.click()
new_url_element=driver.find_element_by_xpath("//a[@href=\"/contacts/new\"]")
new_url_element.click()
time.sleep(5)
contact_firstname_element=driver.find_element_by_xpath("//input[@name='first_name']")
contact_firstname_element.send_keys("Sudarshan")
contact_lastname_element=driver.find_element_by_xpath("//input[@name='last_name']")
contact_lastname_element.send_keys("Govindarajan")
contact_middle_name_element=driver.find_element_by_xpath("//input[@name='middle_name']")
contact_middle_name_element.send_keys("XXX")
contact_company_element=driver.find_element_by_xpath("//div[@name='company']")
contact_company_element.send_keys("Msys")
email_address_element=driver.find_element_by_xpath("//input[@placeholder='Email address']")
email_address_element.send_keys("sudarshan.suraj@yahoo.com")
description_element=driver.find_element_by_xpath("//textarea[@name='description']")
description_element.send_keys("This is used for sample automation testing")
save_element=driver.find_element_by_xpath("//i[@class='save icon']")
save_element.click()